name: build_upload_release

on: [push, pull_request]

jobs:

#= Build D3D11 =======================================================================================================
  build_d3d11:
    runs-on: [windows-2022]    
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Generate project files
        shell: cmd
        run: 'Generate_VS2022_D3D11'       
      
      - name: Build
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" /p:Platform=Windows /p:Configuration=Release /m Spartan.sln'         
      
      - name: Clean up for artifact upload
        shell: bash
        run: ./Scripts/clean.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@master   
        with:
          name: windows_d3d11
          path: out

 #= Build D3D12 =======================================================================================================
  build_d3d12:
    runs-on: [windows-2022]    
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Generate project files
        shell: cmd
        run: 'Generate_VS2022_D3D12'       
     
      - name: Build
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" /p:Platform=Windows /p:Configuration=Release /m Spartan.sln'         
      
      - name: Clean up for artifact upload
        shell: bash
        run: ./Scripts/clean.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@master  
        with:
          name: windows_d3d12
          path: out

#= Build Vulkan ========================================================================================================
  build_vulkan:
    runs-on: [windows-2022]    
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Generate project files
        shell: cmd
        run: 'Generate_VS2022_Vulkan'       
      
      - name: Build
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" /p:Platform=Windows /p:Configuration=Release /m Spartan.sln'         
     
      - name: Clean up for artifact upload
        shell: bash
        run: ./Scripts/clean.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@master  
        with:
          name: windows_vulkan
          path: out

#= Release ===========================================================================================================
  pre-release:
    name: "release"
    runs-on: "ubuntu-latest"
    needs:
      - build_d3d11
      - build_d3d12
      - build_vulkan
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - run: mkdir -p out
      
      - name: Download D3D11 build
        uses: actions/download-artifact@master
        with:
          name: windows_d3d11
          path: out
      
      - name: Download D3D12 build
        uses: actions/download-artifact@master
        with:
          name: windows_d3d12
          path: out
     
      - name: Download Vulkan build
        uses: actions/download-artifact@master
        with:
          name: windows_vulkan
          path: out
      
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
