name: build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2019
    
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
   
      - name: Generate project files
        shell: cmd
        run: |
          Generate_VS19_Project.bat
          
      - name: Build
        shell: cmd
        run: |
          "%MSBUILD_PATH%\MSBuild.exe" /p:Platform=x64 /p:Configuration=Release /m Spartan.sln
          
      - name: Clean up for artifact upload
        shell: cmd
        run: |
          Scripts\clean.bat.bat
 
      - uses: actions/upload-artifact@master  
        with:
          name: release_x64
          path: Binaries\Release
