name: build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2019
    
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
   
      - name: Build x64
        shell: cmd
        run: |
          Generate_VS19_Project.bat
          "%MSBUILD_PATH%\MSBuild.exe" /p:Platform=x64 /p:Configuration=Release Spartan.sln
